<?php
return array(

	'lists' => array(
		'stats' => array(
			'member_count' 	=> array(
				'title'		=> 'Total Membres',
				'desc_en'   => 'The number of active members in the given list.',
				'desc' 		=> "Le nombre total d'inscriptions dans la base de données Mailchimp pour tous les départements de BUT DOM.",
				'icon'		=> 'user',
				'class'		=> 'success',
				'float'		=> 0,
				'active'	=> true,
			),
			'unsubscribe_count' 	=> array(
				'title'		=> 'Désinscrits',
				'desc_en'   => 'The number of members who have unsubscribed from the given list.',
				'desc' 		=> "Le nombre de clients qui se sont désinscrits à la newsletter",
				'icon'		=> 'warning-sign',
				'class'		=> 'danger',
				'float'		=> 0,
				'active'	=> false,
			),
			'cleaned_count' 	=> array(
				'title'		=> 'Cleaned up',
				'desc_en'   => 'The number of members cleaned from the given list.',
				'desc' 		=> "Le nombre de clients qui ont été effacé (spams)",
				'float'		=> 0,
				'active'	=> false,
			),
			'member_count_since_send' 	=> array(
				'title'		=> 'Derniers actifs',
				'desc_en'   => 'The number of active members in the given list since the last campaign was sent',
				'desc' 		=> "Le nombre de clients actifs lors de l'envoie de la dernière campagne.",
				'icon'		=> 'heart',
				'badge'		=> 'success',
				'float'		=> 0,
				'active'	=> true,
			),
			'unsubscribe_count_since_send' 	=> array(
				'title'		=> 'Derniers désinscrits',
				'desc_en'   => 'The number of members who have unsubscribed from the given list since the last campaign was sent',
				'desc' 		=> "Le nombre de clients qui se sont désinscrits à la newsletter lors de l'envoie de la dernière campagne.",
				'icon'		=> 'cloud-download',
				'badge'		=> 'success',
				'float'		=> 0,
				'html'		=> '<div class="separator" />',
				'active'	=> true,
			),
			'avg_sub_rate' 	=> array(
				'title'		=> "Moyenne d'inscriptions",
				'desc_en'   => 'the average number of subscribe per month for the list (empty value if we havent calculated this yet)',
				'desc' 		=> "La moyenne d'inscriptions par mois sur la liste de BUT DOM.",
				'icon'		=> 'thumbs-up',
				'class'		=> 'info',
				'float'		=> 0,
				'active'	=> true,
			),
			'avg_unsub_rate' 	=> array(
				'title'		=> "Moyenne de désinscriptions",
				'desc_en'   => 'the average number of unsubscribe per month for the list (empty value if we havent calculated this yet)',
				'desc' 		=> "La moyenne de désinscriptions par mois sur la liste de BUT DOM.",
				'icon'		=> 'thumbs-down',
				'badge'		=> 'info',
				'float'		=> 0,
				'html'		=> '<div class="separator" />',
				'active'	=> true,
			),
			'campaign_count' 	=> array(
				'title'		=> 'Campagne Newsletters',
				'desc_en'   => 'The number of campaigns in any status that use this list',
				'desc' 		=> "Le nombre de campagnes newsletters ou jeux envoyés sur BUT DOM",
				'icon'		=> 'send',
				'class'		=> 'warning',
				'float'		=> 0,
				'active'	=> true,
			),
			'open_rate' 	=> array(
				'title'		=> "Moyenne Ouvertures (%)",
				'desc_en'   => 'the average open rate per campaign for the list (empty value if we havent calculated this yet)',
				'desc' 		=> "La moyenne de taux d'ouverture sur les campagnes ou jeux pour BUT DOM.",
				'icon'		=> 'eye-open',
				'badge'		=> 'warning',
				'float'		=> 2,
				'active'	=> true,
			),
			'click_rate' 	=> array(
				'title'		=> "Moyenne Clics (%)",
				'desc_en'   => 'the average click rate per campaign for the list (empty value if we havent calculated this yet)',
				'desc' 		=> "La moyenne de taux de clics sur les campagnes ou jeux pour BUT DOM.",
				'icon'		=> 'hand-down',
				'badge'		=> 'warning',
				'float'		=> 2,
				'active'	=> true,
			),
			'cleaned_count_since_send' 	=> array(
				'title'		=> 'Total du dernier cleanup',
				'desc_en'   => 'The number of members cleaned from the given list since the last campaign was sent',
				'desc' 		=> "",
				'float'		=> 0,
				'active'	=> false,
			),
			'grouping_count' 	=> array(
				'title'		=> "Total intérêts",
				'desc_en'   => 'The number of Interest Groupings for this list',
				'desc' 		=> "",
				'float'		=> 0,
				'active'	=> false,
			),
			'group_count' 	=> array(
				'title'		=> 'Total départements',
				'desc_en'   => 'The number of Interest Groups (regardless of grouping) for this list',
				'desc' 		=> "",
				'float'		=> 0,
				'active'	=> false,
			),
			'merge_var_count' 	=> array(
				'title'		=> 'Nombre données spécifique mailchimp',
				'desc_en'   => 'The number of merge vars for this list (not including the required EMAIL one)',
				'desc' 		=> "",
				'float'		=> 0,
				'active'	=> false,
			),
			'target_sub_rate' 	=> array(
				'title'		=> "Objectif inscriptions",
				'desc_en'   => 'the target subscription rate for the list to keep it growing (empty value if we havent calculated this yet)',
				'desc' 		=> "",
				'float'		=> 0,
				'active'	=> false,
			),
		),
	)

);